apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      
      labels:
        app: mysql
    spec:
      containers:

      - env:
        
        # Pull password from secrets
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
       # Load all ConfigMap keys/values into environment variable
        envFrom:
          - configMapRef:
              name: mysql-config-map
        image: mysql:latest
        imagePullPolicy: ""
        name: mysql-docker-container
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /data/mysql
          name: mysql-vol
         # Reference ConfigMap data at appropriate path (/etc/config)  
        - mountPath: /etc/config
          name: mysql-config-vol

      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: mysql-pvc
      # Define volume that will contain ConfigMap data    
      - name: mysql-config-vol
        configMap:
          name: mysql-config-map
status: {}
