apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: taskmanager
  name: taskmanager-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
