apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taskmanager
  name: taskmanager-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  strategy:
    type: Recreate
  template:
    metadata:
     
      labels:
        app: taskmanager
    spec:
      containers:
      - image: techiesantosh/taskmanager:latest
        imagePullPolicy: Always
        name: taskmanager
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 2
          timeoutSeconds: 2
          failureThreshold: 1  
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 2  
          timeoutSeconds: 2
          failureThreshold: 1            
        resources: {}
        volumeMounts:
        - mountPath: /data/taskmanager
          name: taskmanager-pv
        - mountPath: /data/config
          name: taskmanager-config-vol   
        - mountPath: /data/secret
          name: taskmanager-secret-vol   

      restartPolicy: Always
    
      volumes:
      - name: taskmanager-pv
        persistentVolumeClaim:
          claimName: taskmanager-pvc

      - name: taskmanager-config-vol
        configMap:
          name: taskmanager-config-map

      - name: taskmanager-secret-vol
        secret:
          secretName: taskmanager-secret

status: {}
